language: cpp

branches:
  only:
    - travis

compiler:
  - gcc
  - clang


before_install:
    - sudo apt-get update
install:
    - sudo apt-get install python debhelper libz-dev libx11-dev libenchant-dev libmythes-dev autotools-dev libqt4-dev libboost-dev libboost-filesystem-dev libboost-signals-dev libboost-iostreams-dev libboost-regex-dev libboost-test-dev pkg-config tex-common
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
